import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/ui/navbar";

const sfui = localFont({
  src: "./fonts/SF-UI-Display-Regular.ttf",
  variable: "--font-sfui",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfui.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
